### PR TITLE
Top-levels for trees

### LINKED ISSUE #25: Implement a top-level to tree views
Like the ROBOT tree, this top-level should show:
* Classes
* Properties (annotation, data, and object)
* Individuals
* Datatypes

### PR DESCRIPTION
**Pull request by beckyjackson**
Resolves #25 

image

I changed the methods a bit to remove the `terms2rdfa` method. If you passed more than one term to that method, it basically doubled the browser in the same page. I think we will only ever pass one term to the tree method so that's now `build_tree` and accepts a single term ID instead of a list of term IDs. If you do not pass in a term ID, the browser will start at "Class".

This does a lot more checking in python, so I wonder if it would be more beneficial to create a `tmp.terms` table to store hierarchies and entity types? I'm not sure - this is still just as fast as it was before as far as I can tell.

All top level terms (e.g. Class, Annotation Property) display the help page. I got rid of `owl:Thing` because it seemed weird to have Class -> Thing -> the terms we care about.

### CODE REVIEW

**Comment by jamesaoverton** [comment]
Thanks! Can you please add a top-level "Ontology" entry to this PR? I'd like it to appear above Class but as a sibling. On the right it should show the various ontology annotations. I thin that the ID that selects this page should be the CURIE of the ontology IRI. Maybe Gizmos has to check if the ID has type owl:Ontology?

I would still like to default to Class if no ID is provided, like you show.

**Comment by beckyjackson** [comment]
Yep! I made it just `owl:Ontology` to be like the other nodes. We could do the CURIE of the ontology, but I thought this was a little bit easier to handle, especially if there end up being weird characters in the CURIE like slashes or something.

image

**Comment by jamesaoverton** [comment]
Sorry, I don't like `id=owl:Ontology` for this. `owl:Ontology` is its own thing, and we shouldn't be overriding it. The ID should be the ontology CURIE or IRI.

**Comment by beckyjackson** [comment]
If the ID is the full IRI, this causes some issues with href patterns not using query parameters. For example, for the ONTIE update, the pattern is just `./{curie}`. I tried using percent-escaping, and the flask server still tries to interpret the IRI as a path:
```
./%3Chttps%3A%2F%2Fontology.iebd.org%2Fontology%2Fontie.owl%3E
```
... results in a 404 not found.

The dots also cause the flask server to think it's looking for some sort of export format, but I can fix the flask server code to ignore that... Any thoughts on the forward slash issue?

**Comment by jamesaoverton** [comment]
Ok. Let's use a special ID "ontology" for this.

**Comment by beckyjackson** [comment]
OK - done!

**Review by jamesaoverton — APPROVED** [review]

**Pull request merged**
