### PR TITLE
Escape illegal characters in QNames in extract

### LINKED ISSUE #38: Detect invalid QNames in export
`gizmos.extract` created a ttl file with this line in it that won't load with ROBOT:
```
IAO:0020000 IAO:0000412 obo:iao/pno.owl .
```

Another example:
```
GO:0008150 oboInOwl:inSubset obo:go#goslim_yeast .
```

`extract` should check all (?) IRIs and if they are not valid QNames, expand them to full IRIs.

### PR DESCRIPTION
**Pull request by beckyjackson**
Resolves #38 

Replaces illegal characters in local IDs with the escaped character.

### CODE REVIEW

**Comment by jamesaoverton** [comment]
I'd prefer to do this in pure SQL but I expect it will be ugly.

For now, please use [`create_function`](https://docs.python.org/3/library/sqlite3.html#sqlite3.Connection.create_function) to define the check you want, and then run it from within the SQL query. Never tried that before, but it seems neat and should be faster.

**Review by jamesaoverton — CHANGES_REQUESTED** [review]
I'd prefer to do this in pure SQL but expect it will be ugly.

For now, pleas use [`create_function`](https://docs.python.org/3/library/sqlite3.html#sqlite3.Connection.create_function) to define a function in Python that you can call inside SQL. Never tried it before, but it seems like a very neat feature.

**Comment by beckyjackson** [comment]
That's so cool! I've updated it to use that.

**Comment by jamesaoverton** [comment]
Looks good. I'd like some sort of test.

**Comment by beckyjackson** [comment]
OK - I've added an additional axiom to the test that uses `/` in the local ID.

**Review by jamesaoverton — APPROVED** [review]

**Pull request merged**
